#!/bin/bash

SEARCH="$1"
WRITE="$2"

SCRIPT_DIR=$(dirname "$(realpath "$0")")
MAINDB="$(cat $SCRIPT_DIR/maindb.txt)"

if [ -z "$WRITE" ]; then
        hcx-info "$MAINDB" -s 5 | grep -i "$SEARCH"
else
        hcx-info "$MAINDB" -g "$SEARCH" >> fetch.txt
fi
