#!/bin/bash -x
sudo ln -sfr hcx-cap /usr/local/bin/.
sudo ln -sfr hcx-cracker /usr/local/bin/.
sudo ln -sfr hcx-fetch /usr/local/bin/.
sudo ln -sfr hcx-findpass /usr/local/bin/.
sudo ln -sfr hcx-genlst /usr/local/bin/.
sudo ln -sfr hcx-genlst-hswifi /usr/local/bin/.
sudo ln -sfr hcx-genlst-hswifi-pre /usr/local/bin/.
sudo ln -sfr hcx-genlst-hswifi-preall /usr/local/bin/.
sudo ln -sfr hcx-genlst-num8 /usr/local/bin/.
sudo ln -sfr hcx-genlst-numcommon /usr/local/bin/.
sudo ln -sfr hcx-genlst-upper8 /usr/local/bin/.
sudo ln -sfr hcx-hashes2csv /usr/local/bin/.
sudo ln -sfr hcx-info /usr/local/bin/.
sudo ln -sfr hcx-names /usr/local/bin/.
sudo ln -sfr hcx-new /usr/local/bin/.
sudo ln -sfr hcx-potfile /usr/local/bin/.
sudo ln -sfr hcx-rpidump /usr/local/bin/.
sudo ln -sfr hcx-rpidump-wmenu /usr/local/bin/.
sudo ln -sfr hcx-rmhashes /usr/local/bin/.
sudo ln -sfr hcx-status /usr/local/bin/.
sudo ln -sfr hcx-uniq /usr/local/bin/.
sudo ln -sfr hcx-wifi /usr/local/bin/.
sudo ln -sfr hcx-wifi-genpasslst /usr/local/bin/.
sudo ln -sfr hcx-wifi-maconly /usr/local/bin/.
