#!/usr/bin/env python3

import sys

if len(sys.argv) < 2:
    print("ABOUT: print uniq hashes by bssid+essid")
    print("USAGE: " + sys.argv[0] + " <hashesFile>")
    exit()

with open(sys.argv[1], 'r') as file1:
    lines = [line.strip() for line in file1.readlines()]

def hex2str(hex_string):
    try: return bytes.fromhex(hex_string).decode('utf-8')
    except ValueError: return "HEX ERROR"

def line2info(line):
    split = line.split("*")
    hash_id = split[2]
    hash_id, bssid, mac, essid = split[2], split[3], split[4], hex2str(split[5])
    return hash_id, bssid, mac, essid

hashes_dict = {}
for line in lines:
    if not line: continue
    hash_id, bssid, mac, essid = line2info(line)
    key = f"{essid}{bssid}{essid}{bssid}"
    if key not in hashes_dict:
        hashes_dict[key] = line
        print(line)
