#!/usr/bin/env python3
import itertools
import string

# Define the characters to use (lowercase ASCII)
characters = string.ascii_lowercase

# Generate permutations of 4 characters
permutations = itertools.permutations(characters, 4)

# Print the permutations
for p in permutations:
    print(''.join(p))
