#!/usr/bin/env python3

import sys
import argparse
from utils import parse_hash_line, read_lines_from_file, get_unique_key


def parse_arguments():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description='Print unique hashes by BSSID+ESSID combination'
    )
    parser.add_argument('hashes', help='Path to hashes input file')
    return parser.parse_args()

def filter_unique_hashes(lines):
    """Filter and return unique hash lines based on BSSID+ESSID."""
    hashes_dict = {}
    unique_lines = []
    
    for line in lines:
        if not line:
            continue
        
        parsed = parse_hash_line(line)
        if not parsed:
            continue
        
        key = get_unique_key(parsed)
        if key not in hashes_dict:
            hashes_dict[key] = line
            unique_lines.append(line)
    
    return unique_lines


def main():
    """Main execution function."""
    args = parse_arguments()
    
    # Read and process hashes
    lines = read_lines_from_file(args.hashes)
    unique_hashes = filter_unique_hashes(lines)
    
    # Print unique hashes
    for line in unique_hashes:
        print(line)


if __name__ == "__main__":
    main()
