#!/usr/bin/env python3

import argparse
from utils import extract_essids_from_file


def parse_arguments():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description='Print ESSIDs from hash file'
    )
    parser.add_argument('hashes', help='Path to hashes input file')
    return parser.parse_args()


def main():
    """Main execution function."""
    args = parse_arguments()
    
    # Extract and print ESSIDs
    essids = extract_essids_from_file(args.hashes)
    
    for essid in essids:
        print(essid)


if __name__ == "__main__":
    main()

