#!/usr/bin/env python3

import argparse
import subprocess
from utils import line2info

def abgl(bssid):
    result = subprocess.run(["abgl", bssid], capture_output=True, text=True)
    return str(result.stdout).strip()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="geolocate bssid using abgl (https://github.com/0000xFFFF/apple-bssid-geoloc)")
    parser.add_argument('hashes', help="Path to hashes input file")
    args = parser.parse_args()

    with open(args.hashes, 'r', encoding='utf-8') as f:
        lines = f.read().splitlines()

    for line in lines:
        info = line2info(line)
        print(" ".join(info), "--", abgl(info[1]))
